export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_IMAGE_BEGIN = "ADD_IMAGE";
export const ADD_IMAGE_SUCCESS = "ADD_IMAGE_SUCCESS";
export const ADD_IMAGE_ERROR = "ADD_IMAGE_ERROR";

export const CHANGE_BIG_PHOTO = "CHANGE_BIG_PHOTO";
export const DELETE_IMAGE_BEGIN = "DELETE_IMAGE_BEGIN";
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";

export const ADD_PRODUCT_BEGIN = "ADD_PRODUCT_BEGIN";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const GET_ITEMS_BEGIN = "GET_ITEMS_BEGIN";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CHANGE_PAGE = "CHANGE_PAGE";
export const PREPARE_FILTER = "PREPARE_FILTER";

export const GET_SINGLE_OFFER_BEGIN = "GET_SINGLE_OFFER_BEGIN";
export const GET_SINGLE_OFFER_SUCCESS = "GET_SINGLE_OFFER_SUCCESS";
export const GET_SINGLE_OFFER_ERROR = "GET_SINGLE_OFFER_ERROR";
