export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_IMAGE_SUCCESS = "ADD_IMAGE_SUCCESS";
export const ADD_IMAGE_ERROR = "ADD_IMAGE_ERROR";

export const CHANGE_BIG_PHOTO = "CHANGE_BIG_PHOTO";

export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";

export const ADD_OFFER_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_OFFER_ERROR = "ADD_PRODUCT_ERROR";

export const GET_OFFERS_SUCCESS = "GET_ITEMS_SUCCESS";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CHANGE_PAGE = "CHANGE_PAGE";
export const PREPARE_FILTER = "PREPARE_FILTER";

export const GET_SINGLE_OFFER_SUCCESS = "GET_SINGLE_OFFER_SUCCESS";
export const GET_SINGLE_OFFER_ERROR = "GET_SINGLE_OFFER_ERROR";

export const TURN_LOADING_ON = "TURN_LOADING_ON";
export const TURN_LOADING_OFF = "TURN_LOADING_OFF";

export const ADD_USER_ADDRESS_BEGIN = "ADD_USER_ADDRESS";
export const ADD_USER_ADDRESS_SUCCESS = "ADD_USER_ADDRESS";

export const CREATE_ORDER = "CREATE_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";

export const GET_USER_ORDERS = "GET_USER_ORDERS";
