export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_IMAGE_BEGIN = "ADD_IMAGE";
export const ADD_IMAGE_SUCCESS = "ADD_IMAGE_SUCCESS";
export const ADD_IMAGE_ERROR = "ADD_IMAGE_ERROR";

export const CHANGE_BIG_PHOTO = "CHANGE_BIG_PHOTO";
export const DELETE_IMAGE_BEGIN = "DELETE_IMAGE_BEGIN";
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";
